version: "3"

services:

  perros:
    build: ./microservices/perros-service

  premios:
    build: ./microservices/premios-service
 
  razas:
    build: ./microservices/razas-service


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - perros
      - premios
      - razas

